/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package handwrittengui;
import java.net.*;
import java.io.*;
/**
 *
 * @author JCatterson
 */
public class TableWatcher extends javax.swing.JFrame {

    /**
     * Creates new form sendTxt
     */
    public TableWatcher()
    {
        initComponents();        
        connect();
    }
    
    public static void startGUI()
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TableWatcher().setVisible(true);
            }
        });
    }
    
    public void connect()
    {
        try
        {
            requestSocket = new Socket("localhost", 2004);
            out = new ObjectOutputStream(requestSocket.getOutputStream());
            out.flush();            
            
            //in = new ObjectInputStream(requestSocket.getInputStream());
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    
    private void sendMessage(String s)
    {
        try
        {
            out.writeObject(s);
            out.flush();
            
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    public void callThis(String status)
    {
        String s = status + jTextField1.getText();
        sendMessage(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        CleanBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        DirtyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CleanBtn.setText("Cl");
        CleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanBtnActionPerformed(evt);
            }
        });

        DirtyBtn.setText("DI");
        DirtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirtyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CleanBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DirtyBtn))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CleanBtn)
                    .addComponent(DirtyBtn))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void CleanBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        callThis("C-");
    }                                        

    private void DirtyBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        callThis("D-");// TODO add your handling code here:
    }                                        
    private Socket requestSocket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton CleanBtn;
    private javax.swing.JButton DirtyBtn;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
